#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

find $install_dir -type d -exec chmod 755 {} \;
find $install_dir -type f -exec chmod 644 {} \;
chown -R $app:$app $install_dir

#=================================================
# SETUP SSO
#=================================================
ynh_script_progression "Applying SSO patch..."

ynh_config_add --template="include.php" --destination="$install_dir/include.php"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
